name: Update Langsmith Docs Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout langsmith-cookbook
        uses: actions/checkout@v2
        with:
          path: langsmith-cookbook

      - name: Checkout langsmith-docs
        uses: actions/checkout@v2
        with:
          repository: langchain-ai/langsmith-docs
          path: langsmith-docs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes in the submodule
        run: |
          cd langsmith-docs/subdirectories/langsmith-cookbook
          git pull origin main
          cd ../../../ 
          
      - name: Commit changes
        run: |
          cd langsmith-docs 
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add subdirectories/langsmith-cookbook
          git commit -m "Update langsmith-cookbook submodule to latest commit"

      - name: Push changes to a new branch
        run: |
          git push origin HEAD:refs/heads/update-submodule-${{ github.sha }}

      - name: Create Pull Request in langsmith-docs
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: langchain-ai/langsmith-docs
          branch: update-submodule-${{ github.sha }}
          title: "Update langsmith-cookbook submodule"
          body: "This PR updates the langsmith-cookbook submodule to the latest commit."
